export const COMPANY_INFO = {
  name: "KC Welding",
  tagline: "Serving Central Louisiana since 2021",
  phone: "573-301-6131",
  email: "kcwelding175@gmail.com",
  facebook: "https://www.facebook.com/profile.php?id=100089200659448",
  location: "Central Louisiana (mobile services)",
  established: "2021",
};

export const SERVICES = [
  {
    id: "emergency-repair",
    title: "Emergency Repair",
    tagline: "When Time Is Critical, We're There",
    icon: "https://kc-welding.com/wp-content/uploads/2024/08/Untitled-design-152.png",
    image: "https://kc-welding.com/wp-content/uploads/2024/08/322367465_1129072047811402_7048800367314060031_n.jpg",
    description: "At KC Welding, we understand that emergencies can happen at the most inconvenient times, disrupting your daily operations. That's why we offer time-sensitive solutions for all your welding and repair needs.",
    points: [
      "Rapid response for critical breakdowns",
      "On-site mobile service",
      "Available when you need us most",
      "Quality repairs under pressure"
    ]
  },
  {
    id: "torch-cutting",
    title: "Torch Cutting",
    tagline: "Precision Cuts Through Any Metal",
    icon: "https://kc-welding.com/wp-content/uploads/2024/08/Untitled-design-153.png",
    image: "https://kc-welding.com/wp-content/uploads/2024/08/KC-Welding-4-1-scaled.jpeg",
    description: "Our torch cutting services at KC Welding are designed to deliver precision for all your metal fabrication and repair needs. Using high-quality equipment and expert techniques.",
    points: [
      "High-temperature precision cutting",
      "Thick steel plate capability",
      "Custom shapes and specifications",
      "Clean, accurate cuts every time"
    ]
  },
  {
    id: "fabrication",
    title: "Fabrication",
    tagline: "Bringing Your Metalwork Visions to Life",
    icon: "https://kc-welding.com/wp-content/uploads/2024/08/Untitled-design-154.png",
    image: "https://kc-welding.com/wp-content/uploads/2024/08/321611757_498417779059188_2259306759171483200_n.jpg",
    description: "When it comes to bringing your metalwork visions to life, our expert fabrication services are second to none! We specialize in custom metal fabrication that meets your exact specifications.",
    points: [
      "Custom metal fabrication",
      "Small-scale to industrial projects",
      "Design through final assembly",
      "Precision and attention to detail"
    ]
  },
  {
    id: "fence-repair",
    title: "Fence Repair",
    tagline: "Security and Strength Restored",
    icon: "https://kc-welding.com/wp-content/uploads/2024/08/Untitled-design-155.png",
    image: "https://kc-welding.com/wp-content/uploads/2025/12/IMG_9564-scaled.jpg",
    description: "When it comes to keeping your property secure and looking its best, our expert fence repair welding services have you covered!",
    points: [
      "Metal rail repairs",
      "Gate structure reinforcement",
      "High-quality materials",
      "Long-lasting durability"
    ]
  },
  {
    id: "equipment-repair",
    title: "Equipment Repair",
    tagline: "Get Your Machinery Back to Work",
    icon: "https://kc-welding.com/wp-content/uploads/2024/08/Untitled-design-156.png",
    image: "https://kc-welding.com/wp-content/uploads/2024/08/427910016_369080659408620_1393390380739899691_n.jpg",
    description: "When your equipment is down, so is your productivity—don't let that happen! We specialize in top-notch equipment repair services.",
    points: [
      "Heavy machinery repairs",
      "Precision tool restoration",
      "Minimize downtime",
      "Durable, reliable results"
    ]
  },
  {
    id: "trailer-repair",
    title: "Trailer Repair",
    tagline: "Road-Ready Repairs You Can Trust",
    icon: "https://kc-welding.com/wp-content/uploads/2024/08/Untitled-design-158.png",
    image: "https://kc-welding.com/wp-content/uploads/2025/09/IMG_0170-scaled.jpg",
    description: "At KC Welding we provide expert trailer repair services, ensuring your equipment is safe and road-ready.",
    points: [
      "Structural repairs",
      "Hitch and connection work",
      "Heavy-duty durability",
      "Safe and road-ready results"
    ]
  },
  {
    id: "welding-techniques",
    title: "MIG / TIG / STICK / FLUX-CORE",
    tagline: "Every Technique. Every Metal. Every Time.",
    icon: "https://kc-welding.com/wp-content/uploads/2024/08/Untitled-design-159.png",
    image: "https://kc-welding.com/wp-content/uploads/2024/08/KC-Welding-pt-2-2-scaled.jpeg",
    description: "When it comes to top-notch welding services, we've got you covered with a full range of techniques.",
    points: [
      "MIG — Fast, versatile, great for most projects",
      "TIG — Precision work for delicate materials",
      "STICK — Heavy-duty structural applications",
      "FLUX-CORE — Outdoor work and thicker materials"
    ]
  },
  {
    id: "duck-blind",
    title: "Duck Blind",
    tagline: "Custom Built for the Serious Hunter",
    icon: "https://kc-welding.com/wp-content/uploads/2024/08/Untitled-design-160.png",
    image: "https://kc-welding.com/wp-content/uploads/2024/08/Untitled-1200-x-1600-px.png",
    description: "When it comes to duck blind welding, we bring the precision and craftsmanship needed to keep you hidden.",
    points: [
      "Custom-fitted construction",
      "Weather-resistant durability",
      "Repairs and new builds",
      "Built for Louisiana hunting"
    ]
  },
  {
    id: "tractor-modifications",
    title: "Tractor Modifications",
    tagline: "Upgrade Your Machine's Capabilities",
    icon: "https://kc-welding.com/wp-content/uploads/2024/08/Untitled-design-161.png",
    image: "https://kc-welding.com/wp-content/uploads/2025/09/IMG_0644-scaled.jpg",
    description: "Transform your tractor with custom modifications designed to enhance performance and versatility.",
    points: [
      "Custom attachments",
      "Performance upgrades",
      "Structural reinforcements",
      "Built for your specific needs"
    ]
  },
  {
    id: "lean-to",
    title: "Lean-To",
    tagline: "Covered Protection, Built Strong",
    icon: "https://kc-welding.com/wp-content/uploads/2024/08/Untitled-design-154.png",
    image: "https://kc-welding.com/wp-content/uploads/2025/12/IMG_5094-scaled.jpg",
    description: "Need additional covered space? KC Welding constructs sturdy lean-to structures that provide reliable protection.",
    points: [
      "Equipment and vehicle protection",
      "Durable construction",
      "Weather-resistant design",
      "Complements existing structures"
    ]
  },
  {
    id: "metal-building",
    title: "Metal Building",
    tagline: "Structures Built to Stand the Test of Time",
    icon: "https://kc-welding.com/wp-content/uploads/2024/08/Untitled-design-161.png",
    image: "https://kc-welding.com/wp-content/uploads/2025/07/Black-and-Brown-Grand-Opening-Instagram-Post-Facebook-Post.png",
    description: "When it comes to metal building welding, we bring the precision and craftsmanship needed to ensure your structure is strong.",
    points: [
      "Workshops and storage units",
      "Custom facilities",
      "New construction and repairs",
      "Built for long-term durability"
    ]
  }
];

export const GALLERY_IMAGES = [
  '/gallery/IMG_0027.JPG',
  '/gallery/IMG_0396.jpeg',
  '/gallery/IMG_0536.jpeg',
  '/gallery/IMG_0551.jpeg',
  '/gallery/IMG_0553.jpeg',
  '/gallery/IMG_0558.jpeg',
  '/gallery/IMG_0606.jpeg',
  '/gallery/IMG_0621.jpeg',
  '/gallery/IMG_0644.jpeg',
  '/gallery/IMG_0647.jpeg',
  '/gallery/IMG_0699.jpeg',
  '/gallery/IMG_0782.jpeg',
  '/gallery/IMG_1034.jpeg',
  '/gallery/IMG_1118.jpeg',
  '/gallery/IMG_1215.jpeg',
  '/gallery/IMG_1226.jpeg',
  '/gallery/IMG_1233.jpeg',
  '/gallery/IMG_1234.jpeg',
  '/gallery/IMG_1236.jpeg',
  '/gallery/IMG_1239.jpeg',
  '/gallery/IMG_1248.jpeg',
  '/gallery/IMG_1249.jpeg',
  '/gallery/IMG_1251.jpeg',
  '/gallery/IMG_1252.jpeg',
  '/gallery/IMG_1253.jpeg',
  '/gallery/IMG_1758.jpeg',
  '/gallery/IMG_1761.jpeg',
  '/gallery/IMG_1826.jpeg',
  '/gallery/IMG_1847.jpeg',
  '/gallery/IMG_1856.jpeg',
  '/gallery/IMG_1875.jpeg',
  '/gallery/IMG_1876.JPG',
  '/gallery/IMG_1903.jpeg',
  '/gallery/IMG_1950.jpeg',
  '/gallery/IMG_1951.jpeg',
  '/gallery/IMG_2040.jpeg',
  '/gallery/IMG_2073.jpeg',
  '/gallery/IMG_2077.jpeg',
  '/gallery/IMG_2080.jpeg',
  '/gallery/IMG_2081.jpeg',
  '/gallery/IMG_2143.jpeg',
  '/gallery/IMG_2144.jpeg',
  '/gallery/IMG_2145.jpeg',
  '/gallery/IMG_2183.jpeg',
  '/gallery/IMG_2184.jpeg',
  '/gallery/IMG_2197.jpeg',
  '/gallery/IMG_2199.jpeg',
  '/gallery/IMG_2272.jpeg',
  '/gallery/IMG_2273.jpeg',
  '/gallery/IMG_2276.jpeg',
  '/gallery/IMG_2277.jpeg',
  '/gallery/IMG_2278.jpeg',
  '/gallery/IMG_2403.jpeg',
  '/gallery/IMG_2405.jpeg',
  '/gallery/IMG_2409.jpeg',
  '/gallery/IMG_2410.jpeg',
  '/gallery/IMG_2629.jpeg',
  '/gallery/IMG_2630.jpeg',
  '/gallery/IMG_2634.jpeg',
  '/gallery/IMG_2640.jpeg',
  '/gallery/IMG_2697.jpeg',
  '/gallery/IMG_2699.jpeg',
  '/gallery/IMG_2876.jpeg',
  '/gallery/IMG_2877.jpeg',
  '/gallery/IMG_2878.jpeg',
  '/gallery/IMG_2904.jpeg',
  '/gallery/IMG_2933.jpeg',
  '/gallery/IMG_2934.jpeg',
  '/gallery/IMG_2937.jpeg',
  '/gallery/IMG_3020.jpeg',
  '/gallery/IMG_3404.jpeg',
  '/gallery/IMG_3430.jpeg',
  '/gallery/IMG_3436.jpeg',
  '/gallery/IMG_3442.JPG',
  '/gallery/IMG_3451.jpeg',
  '/gallery/IMG_3454.jpeg',
  '/gallery/IMG_3492.jpeg',
  '/gallery/IMG_3506.jpeg',
  '/gallery/IMG_3536.jpeg',
  '/gallery/IMG_3542.jpeg',
  '/gallery/IMG_3563.jpeg',
  '/gallery/IMG_3570.jpeg',
  '/gallery/IMG_3572.jpeg',
  '/gallery/IMG_3576.jpeg',
  '/gallery/IMG_3578.jpeg',
  '/gallery/IMG_3600.jpeg',
  '/gallery/IMG_3603.jpeg',
  '/gallery/IMG_3609.JPG',
  '/gallery/IMG_3610.JPG',
  '/gallery/IMG_3611.jpeg',
  '/gallery/IMG_3624.jpeg',
  '/gallery/IMG_3625.jpeg',
  '/gallery/IMG_3636.jpeg',
  '/gallery/IMG_3637.jpeg',
  '/gallery/IMG_3638.jpeg',
  '/gallery/IMG_3639.jpeg',
  '/gallery/IMG_3646.jpeg',
  '/gallery/IMG_3656.jpeg',
  '/gallery/IMG_3726.jpeg',
  '/gallery/IMG_3727.jpeg',
  '/gallery/IMG_3728.jpeg',
  '/gallery/IMG_8349.jpeg',
  '/gallery/IMG_8350.jpeg',
  '/gallery/IMG_9276.jpeg',
  '/gallery/IMG_9281.jpeg',
  '/gallery/IMG_9284.jpeg',
];

